language: haskell
branches:
  only:
  - master

before_install:
  # Decrypting the dropbox credentials 
  - openssl aes-256-cbc -K $encrypted_3f6e0f4132ed_key -iv $encrypted_3f6e0f4132ed_iv -in .dropbox_uploader.enc -out .dropbox_uploader -d
  - cp .dropbox_uploader $HOME/

install:
  # Installing the dropbox download script
  - cd $HOME
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
  - chmod +x dropbox_uploader.sh
  # downloading the last (latest?) tarball and installing agda
  - AGDATAR=$(./dropbox_uploader.sh list | tail -n 1 | sed 's/^.*\(Agda.*\)$/\1/')
  - ./dropbox_uploader.sh download $AGDATAR .
  - tar -xzvf $AGDATAR
  - cd $( basename $AGDATAR .tar.gz )
  - sudo ./deploy.sh
  # generating Everything.agda
  - cabal install filemanip
  - cd $HOME/build/agda/agda-stdlib
  - runghc GenerateEverything.hs

script:
  # generating index.agda
  - ./index.sh
  # building the docs
  - agda -i . -i src/ --html src/index.agda
  # moving everything at the root
  - mv html/* .

after_success:
  # uploading to gh-pages
  - git init
  - git config --global user.name "Travis CI bot"
  - git config --global user.email "travis-ci-bot@travis.fake"
  - git remote add upstream https://$GH_TOKEN@github.com/agda/agda-stdlib.git &>/dev/null
  - git fetch upstream && git reset upstream/gh-pages
  - git add -f \*.html
  - git commit -m "Automatic HTML update via Travis"
  - git push -q upstream HEAD:gh-pages &>/dev/null

notifications:
  email: false

# Github token
env:
  global:
    secure: f0GRSKTlAw6FdrvkI8LjP5ZhwcGBltJ1t5+nxipqfoR3VczMxcNgXD7bdwtUojFYR48jMs2W+LxEoJcuSH4bsdCeoSfpZ0nU424MDajGh0wuhAbSYKQXPWjFOxwMgC23sCySKhDAZiqN/Wd6orwV1p5JhuJkSCHdVeyUp+hLvIw=
